hostapp-update: Update for hooks 2.0

diff --git a/meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update b/meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update
--- a/meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update
+++ b/meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update
@@ -2,6 +2,20 @@
 
 set -eu
 
+run_current_hooks_and_recover () {
+	if [ "$hooks_rollback" = 1 ]; then
+		# Run the current ones to cleanup the system.
+		echo "Failed to run the new hooks. Running current hooks... "
+		hostapp-update-hooks -f || true
+	else
+		echo "Failed to run the new hooks... "
+	fi
+	# unmount if we have mounted the new rootfs
+	umount $new_rootfs || true
+	echo "Update failed."
+	exit 1
+}
+
 local_image=""
 remote_image=""
 reboot=0
@@ -86,29 +100,38 @@ sync -f "$SYSROOT"
 mv -T "$SYSROOT/hostapps/.new" "$SYSROOT/hostapps/$CONTAINER_ID"
 sync -f "$SYSROOT"
 
-if [ "$hooks" = 1 ]; then
-	# Run the defined hooks in the host OS we update to
-	if balena run --privileged --rm -v /dev:/dev -v /mnt:/mnt -e DURING_UPDATE=1 "$HOSTAPP_IMAGE" hostapp-update-hooks; then
-		echo "New hooks ran successfully."
-	else
-		# Something went wrong with the new hooks.
-		if [ "$hooks_rollback" = 1 ]; then
-			# Run the current ones to cleanup the system.
-			echo "Failed to run the new hooks. Running current hooks... "
-			hostapp-update-hooks || true
-		else
-			echo "Failed to run the new hooks... "
-		fi
-		echo "Update failed."
-		exit 1
-	fi
-fi
-
 # Mark it as current hostapp
 ln -srf "$SYSROOT/hostapps/$CONTAINER_ID" "$SYSROOT/current.new"
 sync -f "$SYSROOT"
 mv -T "$SYSROOT/current.new" "$SYSROOT/current"
 sync -f "$SYSROOT"
+
+if [ "$hooks" = 1 ]; then
+	# Run prehooks from the new OS we are updating to in existing OS environment
+	new_rootfs=$($SYSROOT/current/boot/init -sysroot $SYSROOT)
+	if $new_rootfs/usr/bin/hostapp-update-hooks -b -d "$new_rootfs/etc/hostapp-update-hooks.d/" ; then
+		echo "Pre hooks ran successfully"
+	else
+		run_current_hooks_and_recover
+	fi
+	umount $new_rootfs
+
+	# Run the defined hooks in the host OS we update to in new OS environment
+	if balena run --privileged --rm -v /dev:/dev -v /mnt:/mnt -e DURING_UPDATE=1 "$HOSTAPP_IMAGE" hostapp-update-hooks; then
+		echo "New hooks ran successfully."
+	else
+		run_current_hooks_and_recover
+	fi
+
+	# Run posthooks from the new OS we are updating to in existing OS environment
+	new_rootfs=$($SYSROOT/current/boot/init -sysroot $SYSROOT)
+	if $new_rootfs/usr/bin/hostapp-update-hooks -a -d "$new_rootfs/etc/hostapp-update-hooks.d/"; then
+		echo "Post hooks ran successfully"
+	else
+		run_current_hooks_and_recover
+	fi
+	umount $new_rootfs
+fi
 
 # Mark it as current partition
 cur_counter=0
